### ISSUE TITLE
Setting level for md-header does not work 

### ISSUE THREAD

**Issue by Arxero** [github/markdown-toolbar-element#45] opened 2021-07-21 17:07 UTC
Hello I am looking at this line https://github.com/github/markdown-toolbar-element/blob/731b52a7e400260a693ff745ddf3e5984a42b411/src/index.ts#L116
and 
https://github.com/github/markdown-toolbar-element/blob/731b52a7e400260a693ff745ddf3e5984a42b411/src/index.ts#L121

and I do  it like that in my code

```html
<md-header [attr.level]="1"><gw-toolbar-button [button]="btnType.Header"></gw-toolbar-button></md-header>

```

but it still gives me 3  signs of # like ### is there some bug or I am doing it wrong? Thank you!

**Comment by keithamus** [comment] 2021-09-15 16:26
Hey @Arxero thanks for the issue.

What is the `[attr.level]` syntax? Does this map to an html attribute? In raw html this should be `<md-header level="1">`

**Comment by Arxero** [comment] 2021-09-15 16:37
Yes it does and yet it does not work as expected.
![Screenshot_51](https://user-images.githubusercontent.com/30701352/133473795-3430ef9f-d4db-47b4-96df-f4c6a1195794.png)

**Comment by keithamus** [comment] 2021-09-15 16:43
I would advise you using the Chrome inspector to set a break point inside the code; you may be able to figure out why it is not getting the attribute. I'm not sure I would be able to help without seeing the page or a reduced scope reproduction.

**Comment by koddsson** [comment] 2022-01-04 17:18
Looks like a duplicate of https://github.com/github/markdown-toolbar-element/issues/40? Is this an angular project @Arxero?

**Comment by Arxero** [comment] 2022-01-04 17:25
Yes, it is an angular project, and not sure if it duplicate altho seems like, but tell me if it gets fixed will update and verify and close the issue myself.

**Comment by gmaggiodev** [comment] 2022-04-05 09:48
Hi,
when is planned to be relased on npm?
Thanks

**Closed** 2022-04-05 13:26 UTC
