### ISSUE TITLE
Configurable key for code block insertion

### ISSUE THREAD

**Issue by abraithwaite** [github/markdown-toolbar-element#44] opened 2021-07-06 18:44 UTC
With https://github.com/github/markdown-toolbar-element/pull/37 , the ability to easily navigate to EOL using `ctrl + e` was overridden on many systems.

If not, do you have any idea how this may be overridden with a userscript or the likes?  I don't have much proficiency in front-end code, so I wouldn't know where to start doing something like that.  However, this is disruptive enough that I'd be willing to put in the effort to make it work.  It's about ergonomics.

**Comment by keithamus** [comment] 2021-09-15 16:29
This is somewhat a duplicate of #51. I think we can safely close this as it is being worked on.

**Closed by keithamus** 2021-09-15 16:29 UTC
